# Generated by Django 5.0 on 2024-01-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stencil_nr', models.CharField(max_length=20)),
                ('medical_facility', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=300)),
                ('cui', models.CharField(max_length=20)),
                ('phone_nr', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('insurance_house', models.CharField(max_length=50)),
                ('insurance_house_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patient_type', models.CharField(max_length=20)),
                ('card_nr', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other'), (3, 'Ambulanta'), (4, 'Altele'), (5, 'Medic de familie')], max_length=1)),
                ('series', models.CharField(max_length=20)),
                ('nr', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_contract_nr', models.CharField(blank=True, max_length=20, null=True)),
                ('patientInsuranceHouse', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Prescris/Activ'), (2, 'Eliberat')], default=1)),
                ('signature', models.CharField(default='a', max_length=150)),
                ('treatment_days', models.IntegerField()),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.patient')),
                ('presciptor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.medic')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr', models.IntegerField()),
                ('drug_code', models.CharField(max_length=20)),
                ('active_substance', models.CharField(max_length=150)),
                ('concentration', models.CharField(max_length=30)),
                ('pharmaceutical_form', models.CharField(max_length=100)),
                ('disease_code', models.CharField(max_length=20)),
                ('diagnostic_type', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('dose', models.CharField(max_length=20)),
                ('copayment_list_type', models.CharField(max_length=20)),
                ('copayment_list_percent', models.IntegerField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescription')),
            ],
        ),
    ]
