# Generated by Django 5.0 on 2024-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cnp',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
