# Generated by Django 5.0 on 2024-01-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_patient_cnp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='active_substance',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='source',
            field=models.IntegerField(choices=[(0, 'Medic de familie'), (1, 'Ambulatoriu'), (2, 'Spital'), (3, 'Ambulanta'), (4, 'Altele'), (5, 'MF - MM')], max_length=1),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='concentration',
            field=models.CharField(default='10 mg', max_length=30),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='copayment_list_percent',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='copayment_list_type',
            field=models.CharField(default='G15', help_text='Codul listei de bolii, ex.G15 - BOLI PSIHICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='diagnostic_type',
            field=models.CharField(choices=[('Cr.', 'Cronic'), ('SAct.', 'Subacut'), ('Act.', 'Acut')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='disease_code',
            field=models.CharField(choices=[('321', 'Episod depresiv'), ('377', 'Tulburari de somn'), ('504', 'Gripa cu virus identificat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dose',
            field=models.CharField(default='1-0-1/zi', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='drug_code',
            field=models.CharField(choices=[('N05CF02', 'ZOLPIDEMUM'), ('N06AB03', 'FLUOXETINUM'), ('N06AB06', 'SERTRALINUM'), ('N06AB08', 'FLUVOXAMINUM'), ('N06AX21', 'DULOXETINUM')], max_length=150),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='pharmaceutical_form',
            field=models.CharField(choices=[('COMPR.', 'COMPRIMATE'), ('CAPS.', 'CAPSULE'), ('INJ.', 'INJECTII'), ('SOLUT.', 'SOLUTII')], max_length=100),
        ),
    ]
