# Generated by Django 5.0 on 2024-01-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_prescriptionitem_active_substance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patientInsuranceHouse',
        ),
    ]
