# Generated by Django 5.0 on 2024-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_patient_insurance_house_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='signature',
            new_name='patient_signature',
        ),
        migrations.AddField(
            model_name='prescription',
            name='presciptor_signature',
            field=models.CharField(default='a', max_length=170),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='disease_code',
            field=models.CharField(choices=[('321', '321 - Episod depresiv'), ('377', '377 - Tulburari de somn'), ('504', '504 - Gripa cu virus identificat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='drug_code',
            field=models.CharField(choices=[('N05CF02', 'N05CF02 - ZOLPIDEMUM'), ('N06AB03', 'N05CF02 - FLUOXETINUM'), ('N06AB06', 'N05CF02 - SERTRALINUM'), ('N06AB08', 'N05CF02 - FLUVOXAMINUM'), ('N06AX21', 'N05CF02 - DULOXETINUM')], max_length=150),
        ),
    ]
