# Generated by Django 5.0 on 2024-01-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_rename_signature_prescription_patient_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='presciptor_signature',
        ),
    ]
