# Generated by Django 5.0 on 2024-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_remove_medic_public_key_patient_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
