# Generated by Django 5.0 on 2024-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_sale_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateField(),
        ),
    ]
